"use client";

import DashboardLayout from "@/components/Dashboard/DashboardLayout";
import { useAuth } from "@/context/AuthContext";
import { useAppGuard } from "@/hooks/useAppGuard";
import api from "@/lib/axios";
import { AlertCircle,ArrowRight,BriefcaseBusiness,RefreshCw,Search,TrendingUp } from "lucide-react";
import Link from "next/link";
import { useCallback,useEffect,useMemo,useState } from "react";
import styles from "./page.module.css";

type Score={score:number;grade:string;components:{demandScore:number;supplyScore:number;fillRateScore:number;competitionScore:number};meta:{openRequests:number;eligibleTutors:number;fillRate:number;avgOffersPerRequest:number;avgSessionPrice:number;sampleSize:number}};
type Segment={key:string;city:string;subject:string;mode:string;score:Score;opportunity:number};

export default function TutorOpportunitiesPage(){
 const {user}=useAuth(); const guard=useAppGuard(); const [scores,setScores]=useState<Record<string,Score>>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [query,setQuery]=useState(""); const [mode,setMode]=useState("all");
 const load=useCallback(async()=>{if(!user||user.role!=="tutor")return;setLoading(true);setError("");try{const response=await api.get("/liquidity/overview",{params:{countryCode:user.countryCode||"PK"}});setScores(response.data?.scores||{});}catch{setError("Opportunity data could not be loaded.");}finally{setLoading(false);}},[user]);
 useEffect(()=>{void load();},[load]);
 const segments=useMemo<Segment[]>(()=>Object.entries(scores).map(([key,score])=>{const [city="Unknown",subject="Tutoring",segmentMode="online"]=key.split("|");const scarcity=score.meta.openRequests/Math.max(score.meta.eligibleTutors,1);const opportunity=Math.min(100,Math.round(score.components.demandScore*.65+Math.min(scarcity*20,35)));return{key,city,subject,mode:segmentMode,score,opportunity};}).filter(item=>(mode==="all"||item.mode===mode)&&`${item.city} ${item.subject}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>b.opportunity-a.opportunity),[mode,query,scores]);
 if(guard!=="ok"||!user)return null;
 if(user.role!=="tutor")return <DashboardLayout><section className={styles.denied}><AlertCircle/><h1>Tutor access only</h1><p>This workspace is available to approved tutors.</p><Link href="/dashboard">Return to dashboard</Link></section></DashboardLayout>;
 return <DashboardLayout><main className={styles.page}><header className={styles.hero}><div><p className={styles.eyebrow}><TrendingUp size={16} aria-hidden="true"/>Tutor market intelligence</p><h1>Teaching opportunities</h1><p>Find subjects and locations with active student demand. Scores use anonymized marketplace activity from the last 30 days.</p></div><button onClick={()=>void load()} disabled={loading}><RefreshCw size={17} aria-hidden="true"/>{loading?"Refreshing…":"Refresh"}</button></header>
 <section className={styles.explainer} aria-label="How opportunity scores work"><BriefcaseBusiness aria-hidden="true"/><div><strong>Opportunity score</strong><p>Higher scores indicate stronger recent demand relative to currently eligible tutor supply. They are directional signals, not guaranteed work.</p></div></section>
 <div className={styles.toolbar}><label><Search size={17} aria-hidden="true"/><span className={styles.srOnly}>Search city or subject</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search city or subject"/></label><label><span>Teaching mode</span><select value={mode} onChange={event=>setMode(event.target.value)}><option value="all">All modes</option><option value="online">Online</option><option value="in-person">In person</option></select></label></div>
 {error?<div className={styles.error} role="alert"><AlertCircle aria-hidden="true"/><div><strong>Unable to load opportunities</strong><p>{error}</p><button onClick={()=>void load()}>Try again</button></div></div>:loading?<div className={styles.loading} aria-label="Loading teaching opportunities">{[1,2,3].map(item=><span key={item}/>)}</div>:segments.length===0?<section className={styles.empty}><h2>No observed opportunities match</h2><p>Try another filter or browse live tuition requests directly.</p><Link href="/browse-requests">Browse requests</Link></section>:<section className={styles.grid} aria-label="Ranked teaching opportunities">{segments.map((item,index)=><article className={styles.card} key={item.key}><div className={styles.rank}>#{index+1}</div><div className={styles.cardTitle}><div><h2>{item.subject}</h2><p>{item.city} · {item.mode}</p></div><strong>{item.opportunity}<small>/100</small></strong></div><div className={styles.meter} role="meter" aria-label={`${item.subject} opportunity score`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={item.opportunity}><i style={{width:`${item.opportunity}%`}}/></div><dl><div><dt>Open requests</dt><dd>{item.score.meta.openRequests}</dd></div><div><dt>Eligible tutors</dt><dd>{item.score.meta.eligibleTutors}</dd></div><div><dt>Offers per request</dt><dd>{item.score.meta.avgOffersPerRequest}</dd></div><div><dt>Observed rate</dt><dd>{item.score.meta.avgSessionPrice?`PKR ${item.score.meta.avgSessionPrice.toLocaleString()}`:"Limited data"}</dd></div></dl><p className={styles.sample}>Based on {item.score.meta.sampleSize} marketplace observations.</p><Link href={`/browse-requests?city=${encodeURIComponent(item.city)}&subject=${encodeURIComponent(item.subject)}&teachingMode=${encodeURIComponent(item.mode)}`}>View matching requests <ArrowRight size={16} aria-hidden="true"/></Link></article>)}</section>}
 </main></DashboardLayout>;
}
