"use client";
import api from "@/lib/axios";
import { AlertCircle,ArrowLeft,Filter,RefreshCw,Search,TrendingUp } from "lucide-react";
import Link from "next/link";
import { useCallback,useEffect,useMemo,useState } from "react";
import styles from "./page.module.css";

type Score={score:number;grade:"High"|"Moderate"|"Low"|"Very Low";components:{demandScore:number;supplyScore:number;fillRateScore:number;competitionScore:number};meta:{openRequests:number;eligibleTutors:number;fillRate:number;avgOffersPerRequest:number;avgSessionPrice:number;sampleSize:number}};
type Segment={key:string;city:string;subject:string;mode:string;value:Score};
type Summary={avgScore:number;totalSegments:number;high:number;moderate:number;low:number};
const EMPTY:Summary={avgScore:0,totalSegments:0,high:0,moderate:0,low:0};

export default function AdminLiquidityPage(){
 const [scores,setScores]=useState<Record<string,Score>>({}); const [summary,setSummary]=useState(EMPTY); const [countryCode,setCountryCode]=useState("PK"); const [query,setQuery]=useState(""); const [mode,setMode]=useState("all"); const [grade,setGrade]=useState("all"); const [sort,setSort]=useState("score-desc"); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [refreshedAt,setRefreshedAt]=useState<Date|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await api.get("/liquidity/overview",{params:{countryCode}});setScores(response.data?.scores||{});setSummary({...EMPTY,...(response.data?.summary||{})});setRefreshedAt(new Date());}catch{setError("Liquidity data could not be loaded. Check the marketplace API and try again.");}finally{setLoading(false);}},[countryCode]);
 useEffect(()=>{void load();},[load]);
 const rows=useMemo(()=>{const needle=query.trim().toLocaleLowerCase();const segments:Segment[]=Object.entries(scores).map(([key,value])=>{const [city="Unknown",subject="Unknown",segmentMode="unknown"]=key.split("|");return{key,city,subject,mode:segmentMode,value};}).filter(segment=>(!needle||`${segment.city} ${segment.subject}`.toLocaleLowerCase().includes(needle))&&(mode==="all"||segment.mode===mode)&&(grade==="all"||segment.value.grade===grade));return segments.sort((a,b)=>sort==="score-asc"?a.value.score-b.value.score:sort==="demand-desc"?b.value.meta.openRequests-a.value.meta.openRequests:sort==="supply-asc"?a.value.meta.eligibleTutors-b.value.meta.eligibleTutors:b.value.score-a.value.score);},[grade,mode,query,scores,sort]);
 return <main className={styles.page}><header className={styles.header}><div><Link href="/admin" className={styles.back}><ArrowLeft aria-hidden size={16}/>Control Tower</Link><p className={styles.eyebrow}>Market intelligence</p><h1>Marketplace liquidity</h1><p className={styles.intro}>Inspect real city, subject, and teaching-mode segments using demand, eligible supply, fill rate, and offer competition.</p></div><div className={styles.headerActions}><label>Country code<input value={countryCode} maxLength={2} onChange={e=>setCountryCode(e.target.value.toUpperCase().replace(/[^A-Z]/g,""))} aria-describedby="country-help"/></label><button type="button" onClick={()=>void load()} disabled={loading||countryCode.length!==2} className={styles.refresh}><RefreshCw aria-hidden size={16}/>{loading?"Refreshing...":"Refresh data"}</button><span id="country-help" className={styles.srOnly}>Enter a two-letter ISO country code.</span></div></header>
 <section className={styles.summaryGrid} aria-label="Liquidity summary">{[[summary.avgScore,"Average score","Current segment health"],[summary.totalSegments,"Observed segments","No artificial combinations"],[summary.high,"High liquidity","Score 75 or above"],[summary.moderate,"Moderate","Score from 50 to 74"],[summary.low,"Needs attention","Score below 50"]].map(([value,label,hint])=><article key={String(label)} className={styles.metric}><span>{label}</span><strong>{value}</strong><small>{hint}</small></article>)}</section>
 <section className={styles.workspace} aria-busy={loading}><div className={styles.toolbar}><label className={styles.search}><Search aria-hidden size={17}/><span className={styles.srOnly}>Search segments</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search city or subject"/></label><label><Filter aria-hidden size={15}/><span>Mode</span><select value={mode} onChange={e=>setMode(e.target.value)}><option value="all">All modes</option><option value="online">Online</option><option value="in-person">In person</option></select></label><label><span>Grade</span><select value={grade} onChange={e=>setGrade(e.target.value)}><option value="all">All grades</option><option>High</option><option>Moderate</option><option>Low</option><option>Very Low</option></select></label><label><span>Sort</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="score-desc">Score: high to low</option><option value="score-asc">Score: low to high</option><option value="demand-desc">Most open requests</option><option value="supply-asc">Lowest tutor supply</option></select></label></div>
 {refreshedAt&&!error&&<p className={styles.freshness} aria-live="polite">Updated {refreshedAt.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})} · showing {rows.length} of {summary.totalSegments} segments</p>}
 {error?<div className={styles.error} role="alert"><AlertCircle aria-hidden/><div><strong>Unable to load liquidity</strong><p>{error}</p><button type="button" onClick={()=>void load()}>Try again</button></div></div>:loading?<div className={styles.skeletons} aria-label="Loading liquidity segments">{Array.from({length:5},(_,i)=><div key={i}/>)}</div>:rows.length===0?<div className={styles.empty}><div><strong>No matching segments</strong><p>Adjust the filters or use a country with active marketplace demand.</p></div></div>:<div className={styles.tableScroller}><table><caption className={styles.srOnly}>Marketplace liquidity segments and score components</caption><thead><tr><th>Segment</th><th>Score</th><th>Demand / supply</th><th>Fill rate</th><th>Competition</th><th>Rate / sample</th></tr></thead><tbody>{rows.map(segment=><tr key={segment.key}><td><strong>{segment.city}</strong><span>{segment.subject} · {segment.mode}</span></td><td><span className={`${styles.grade} ${styles[segment.value.grade.replace(" ","").toLocaleLowerCase()]}`}>{segment.value.score}/100 · {segment.value.grade}</span></td><td><strong>{segment.value.meta.openRequests} / {segment.value.meta.eligibleTutors}</strong><span>open requests / eligible tutors</span></td><td><strong>{Math.round(segment.value.meta.fillRate*100)}%</strong><ScoreBar value={segment.value.components.fillRateScore} label="Fill-rate component"/></td><td><strong>{segment.value.meta.avgOffersPerRequest}</strong><span>offers per request</span></td><td><strong>{segment.value.meta.avgSessionPrice?`PKR ${segment.value.meta.avgSessionPrice.toLocaleString()}`:"Not enough data"}</strong><span>sample {segment.value.meta.sampleSize}</span><details><summary>Score detail</summary><div className={styles.breakdown}><ScoreBar value={segment.value.components.demandScore} label="Demand"/><ScoreBar value={segment.value.components.supplyScore} label="Supply"/><ScoreBar value={segment.value.components.competitionScore} label="Competition"/></div></details></td></tr>)}</tbody></table></div>}</section><p className={styles.note}><TrendingUp aria-hidden size={15}/>Liquidity scores are operational signals, not guarantees. Use At-Risk Requests for case-level intervention.</p></main>;
}
function ScoreBar({value,label}:{value:number;label:string}){return <span className={styles.barWrap}><span>{label}</span><span className={styles.bar} role="meter" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={value}><i style={{width:`${value}%`}}/></span><b>{value}</b></span>}
